name: Deploy Express App

on:
  push:
    branches: ["main"]

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: print variable
        run: echo "${{ vars.NAME}}"

      - name: setup
        uses: actions/setup-node@v4
        with:
          node-version: '18'