name: "Deploy codigofacilito" # Nombre del workflow

# Trigger que indica cuando se ejecuta el workflow
on:
  push: # Cuando se hace
    branches: ["main"] # En la rama main

jobs:
  deploy-codigofacilito: # Nombre del job, se puede tener varios jobs en un workflow
    runs-on: ubuntu-latest # Indica donde se va a ejecutar
    steps: # Pasos que se van a ejecutar de forma secuencial
      run: echo "Hacemos pull del codigo"
      run: echo "Correr migraciones"
      run: echo "Generar binario"
      run: echo "Publicar version"