name: Deploy Express App

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    # Contenedor de Docker
    # services:
    #   redis:
    #     image: redis
    #     ports:
    #       - 6379:6379

    steps:
      # Relacionado al container creado
      # - name: Instalar redis cli
      #   run: sudo apt-get update -y && sudo apt-get install redis-tools -y

      # - name: Test redis
      #   run: redis-cli -h localhost -p 6379 ping

      - name: print variable
        run: echo "${{ vars.NAME}}" # Contexto para obtener valor de env del repo

      - name: checkout
        uses: actions/checkout@v4

      - name: setup
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Run Test
        run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: deploy
        run: echo "Deploy..."